// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {analyzerpipe} from '../models';
import {topology} from '../models';
import {agent} from '../models';
import {bughub} from '../models';
import {analyzer} from '../models';
import {generator} from '../models';
import {discover} from '../models';
import {doctor} from '../models';
import {cchub} from '../models';
import {labelprobe} from '../models';
import {dsprobe} from '../models';
import {deploy} from '../models';

export function AckIncidentWorkflowReminder(arg1:main.AckIncidentWorkflowReminderInput):Promise<void>;

export function Analyze(arg1:string,arg2:string,arg3:boolean):Promise<analyzerpipe.Result>;

export function AnalyzeServiceTopology(arg1:string,arg2:Record<string, string>):Promise<topology.Snapshot>;

export function AnalyzeV2(arg1:main.AnalyzeInput):Promise<analyzerpipe.Result>;

export function ApplyBot(arg1:string,arg2:string,arg3:boolean):Promise<agent.Result>;

export function ApproveIncidentFix(arg1:main.ApproveIncidentFixInput):Promise<bughub.IncidentCase>;

export function ApproveIncidentMerge(arg1:main.ApproveIncidentMergeInput):Promise<bughub.IncidentCase>;

export function BugHookBaseURL():Promise<string>;

export function CancelAnalyze():Promise<boolean>;

export function CancelBugInvestigation(arg1:main.BugInvestigationCancelInput):Promise<void>;

export function CancelIncidentAttempt(arg1:main.CancelIncidentAttemptInput):Promise<bughub.IncidentCase>;

export function CancelInstall():Promise<boolean>;

export function ChatDeleteKey(arg1:string):Promise<void>;

export function ChatDeleteProviderKey(arg1:string):Promise<void>;

export function ChatLoadKey(arg1:string):Promise<main.ChatLoadKeyResult>;

export function ChatLoadProviderKey(arg1:string):Promise<main.ChatLoadKeyResult>;

export function ChatSaveKey(arg1:string,arg2:string):Promise<void>;

export function ChatSaveProviderKey(arg1:string,arg2:string):Promise<void>;

export function ClearBugPlatformLogin(arg1:main.BugLoginInput):Promise<main.BugLoginResult>;

export function ContinueBugInvestigation(arg1:main.BugInvestigationContinueInput):Promise<bughub.InvestigationRun>;

export function ContinueIncidentCase(arg1:main.ContinueIncidentCaseInput):Promise<bughub.IncidentCase>;

export function DefaultDestPath(arg1:string,arg2:string):Promise<string>;

export function DeleteBugPlatform(arg1:main.BugPlatformDeleteInput):Promise<void>;

export function DeleteInfraCred(arg1:string):Promise<void>;

export function DetectAITools():Promise<main.AIToolsDetectResult>;

export function DetectOpenClawModels(arg1:string):Promise<main.OpenClawDetectResult>;

export function DetectSubmodulesForRepo(arg1:string):Promise<Array<analyzer.SubmoduleHint>>;

export function Diff(arg1:string,arg2:string):Promise<generator.Plan>;

export function DiscoverBots(arg1:Array<string>):Promise<Array<discover.DiscoveredAgent>>;

export function Doctor(arg1:string,arg2:string):Promise<doctor.Report>;

export function FetchBugByID(arg1:main.BugFetchInput):Promise<bughub.SyncResult>;

export function FetchConfigContent(arg1:main.CCHubFetchContentInput):Promise<cchub.FetchContentResult>;

export function FetchConfigContentBatch(arg1:main.CCHubFetchBatchInput):Promise<cchub.FetchBatchResult>;

export function ForgetGhostBot(arg1:string,arg2:string):Promise<void>;

export function Gen(arg1:string,arg2:string):Promise<generator.GenSummary>;

export function GenPreview(arg1:string):Promise<main.GenPreviewResult>;

export function GenerateBugContext(arg1:main.BugContextInput):Promise<string>;

export function GetIncidentCase(arg1:string):Promise<main.IncidentCaseDetail>;

export function GetIncidentWorkflowMetrics():Promise<bughub.WorkflowMetrics>;

export function GetMissingRepoPaths(arg1:string):Promise<main.MissingRepoPathsResult>;

export function GetRemoteURL(arg1:string):Promise<string>;

export function GetRepoPathsForSystem(arg1:string):Promise<Record<string, string>>;

export function GetUserConfig():Promise<main.UserConfigResult>;

export function ImportAndDeploy(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:Record<string, string>):Promise<agent.Result>;

export function KuboardFetchConfigMaps(arg1:main.KuboardFetchBatchInput):Promise<main.KuboardFetchBatchResult>;

export function KuboardGetPodLogs(arg1:main.KuboardGetPodLogsInput):Promise<string>;

export function KuboardListDeployments(arg1:main.KuboardListPodsInput):Promise<Array<main.KuboardDeploymentInfo>>;

export function KuboardListEvents(arg1:main.KuboardListEventsInput):Promise<Array<main.KuboardEvent>>;

export function KuboardListPods(arg1:main.KuboardListPodsInput):Promise<Array<main.KuboardPodInfo>>;

export function KuboardListResources(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.KuboardResources>;

export function KuboardListServices(arg1:main.KuboardListPodsInput):Promise<Array<main.KuboardServiceInfo>>;

export function KuboardPodSnapshot(arg1:main.KuboardPodSnapshotInput):Promise<main.KuboardPodSnapshotResult>;

export function ListBotWorkspaceFiles(arg1:string):Promise<main.FileNode>;

export function ListBranchesForRepo(arg1:string):Promise<Array<string>>;

export function ListBugInvestigationRuns(arg1:string):Promise<Array<bughub.InvestigationRun>>;

export function ListBugPlatforms():Promise<Array<bughub.PlatformConfig>>;

export function ListBugs():Promise<Array<bughub.Bug>>;

export function ListGrafanaDatasources(arg1:main.LokiAuthInput):Promise<Array<labelprobe.Datasource>>;

export function ListIncidentCases():Promise<Array<bughub.IncidentCase>>;

export function ListLokiLabelValues(arg1:main.LokiAuthInput,arg2:string,arg3:string):Promise<labelprobe.ValuesResult>;

export function ListLokiLabels(arg1:main.LokiAuthInput):Promise<labelprobe.LabelsResult>;

export function ListPendingIncidentWorkflowReminders():Promise<Array<bughub.WorkflowReminder>>;

export function LoadInfraCred(arg1:string):Promise<main.ChatLoadKeyResult>;

export function LoginBugPlatform(arg1:main.BugLoginInput):Promise<main.BugLoginResult>;

export function MatchBugBots(arg1:string):Promise<Array<bughub.BotMatch>>;

export function NotifyIncidentDeployed(arg1:main.NotifyIncidentDeployedInput):Promise<bughub.IncidentCase>;

export function One2AllFetchConfigMaps(arg1:string,arg2:string,arg3:Array<main.One2AllConfigMapEntry>):Promise<Array<main.One2AllConfigMapResult>>;

export function One2AllListDeployments(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.One2AllDeployments>;

export function One2AllListResources(arg1:string,arg2:string,arg3:boolean):Promise<main.One2AllResources>;

export function OpenDir(arg1:string):Promise<string>;

export function OpenYAML():Promise<main.OpenYAMLResult>;

export function PathExists(arg1:string):Promise<boolean>;

export function Plan(arg1:string):Promise<generator.Plan>;

export function PrefillCreds(arg1:string):Promise<Record<string, string>>;

export function PreloadConfigCenter(arg1:main.CCHubPreloadInput):Promise<cchub.Result>;

export function PreviewBugAttachment(arg1:main.BugAttachmentPreviewInput):Promise<main.BugAttachmentPreviewResult>;

export function ProbeDataStore(arg1:main.DSProbeInput):Promise<dsprobe.Result>;

export function ProbeURL(arg1:string):Promise<dsprobe.Result>;

export function ProbeURLAuth(arg1:string,arg2:string,arg3:string,arg4:string):Promise<dsprobe.Result>;

export function QuitApp():Promise<void>;

export function ReadBotWorkspaceFile(arg1:string,arg2:string):Promise<main.ReadFileResult>;

export function ReadEnv(arg1:string):Promise<Record<string, string>>;

export function RecommendRoleForRepo(arg1:string,arg2:string,arg3:string):Promise<analyzer.RoleHint>;

export function ReindexCodeGraph(arg1:string,arg2:Record<string, string>):Promise<agent.CodeGraphIndexReport>;

export function ResetIncidentCase(arg1:main.ResetIncidentCaseInput):Promise<bughub.IncidentCase>;

export function RevealInFinder(arg1:string):Promise<void>;

export function RunInstall(arg1:string,arg2:Record<string, string>):Promise<main.RunInstallResult>;

export function SaveBugPlatform(arg1:main.BugPlatformInput):Promise<bughub.PlatformConfig>;

export function SaveBugSelectedBot(arg1:main.BugSelectedBotInput):Promise<bughub.Bug>;

export function SaveInfraCred(arg1:string,arg2:string):Promise<void>;

export function SaveInfraCredBatch(arg1:main.InfraCredBatchInput):Promise<void>;

export function SaveRepoPathsForSystem(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SaveYAML(arg1:string,arg2:string):Promise<string>;

export function ScanInstallPrompts(arg1:string):Promise<Array<deploy.Prompt>>;

export function SelfTestAgent(arg1:string):Promise<agent.SelfTestResult>;

export function SetDefaultReposRoot(arg1:string):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function SnoozeIncidentWorkflowReminder(arg1:main.SnoozeIncidentWorkflowReminderInput):Promise<void>;

export function StartBugFix(arg1:main.BugFixInput):Promise<bughub.InvestigationRun>;

export function StartBugInvestigation(arg1:main.BugInvestigationInput):Promise<bughub.InvestigationRun>;

export function StartIncidentCase(arg1:main.StartIncidentCaseInput):Promise<bughub.IncidentCase>;

export function SyncBugPlatform(arg1:string):Promise<bughub.SyncResult>;

export function UninstallAgent(arg1:string):Promise<agent.UninstallOpenclawResult>;

export function UninstallBot(arg1:string,arg2:string):Promise<main.UninstallBotResult>;

export function Validate(arg1:string):Promise<main.ValidateResult>;

export function Version():Promise<string>;

export function WriteBotWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<void>;
