// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyzerpipe} from '../models';
import {agent} from '../models';
import {generator} from '../models';
import {discover} from '../models';
import {doctor} from '../models';
import {main} from '../models';
import {deploy} from '../models';
import {standalone} from '../models';

export function Analyze(arg1:string,arg2:string,arg3:boolean):Promise<analyzerpipe.Result>;

export function ApplyBot(arg1:string,arg2:string,arg3:boolean):Promise<agent.Result>;

export function CancelInstall():Promise<boolean>;

export function Diff(arg1:string,arg2:string):Promise<generator.Plan>;

export function DiscoverBots(arg1:Array<string>):Promise<Array<discover.DiscoveredAgent>>;

export function Doctor(arg1:string,arg2:string):Promise<doctor.Report>;

export function Gen(arg1:string,arg2:string):Promise<generator.GenSummary>;

export function ImportAndDeploy(arg1:string,arg2:string,arg3:string):Promise<agent.Result>;

export function OpenDir(arg1:string):Promise<string>;

export function OpenYAML():Promise<main.OpenYAMLResult>;

export function Plan(arg1:string):Promise<generator.Plan>;

export function ReadEnv(arg1:string):Promise<Record<string, string>>;

export function RevealInFinder(arg1:string):Promise<void>;

export function RunInstall(arg1:string,arg2:Record<string, string>):Promise<main.RunInstallResult>;

export function SaveYAML(arg1:string,arg2:string):Promise<string>;

export function ScanInstallPrompts(arg1:string):Promise<Array<deploy.Prompt>>;

export function StandaloneStatus(arg1:string):Promise<standalone.Status>;

export function StartStandalone(arg1:string,arg2:string):Promise<main.StartStandaloneResult>;

export function StopStandalone(arg1:string):Promise<boolean>;

export function Validate(arg1:string):Promise<main.ValidateResult>;

export function Version():Promise<string>;
