// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2, arg3) {
  return window['go']['main']['App']['Analyze'](arg1, arg2, arg3);
}

export function AnalyzeV2(arg1) {
  return window['go']['main']['App']['AnalyzeV2'](arg1);
}

export function ApplyBot(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyBot'](arg1, arg2, arg3);
}

export function BugHookBaseURL() {
  return window['go']['main']['App']['BugHookBaseURL']();
}

export function CancelAnalyze() {
  return window['go']['main']['App']['CancelAnalyze']();
}

export function CancelBugInvestigation(arg1) {
  return window['go']['main']['App']['CancelBugInvestigation'](arg1);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function ChatDeleteKey(arg1) {
  return window['go']['main']['App']['ChatDeleteKey'](arg1);
}

export function ChatDeleteProviderKey(arg1) {
  return window['go']['main']['App']['ChatDeleteProviderKey'](arg1);
}

export function ChatLoadKey(arg1) {
  return window['go']['main']['App']['ChatLoadKey'](arg1);
}

export function ChatLoadProviderKey(arg1) {
  return window['go']['main']['App']['ChatLoadProviderKey'](arg1);
}

export function ChatSaveKey(arg1, arg2) {
  return window['go']['main']['App']['ChatSaveKey'](arg1, arg2);
}

export function ChatSaveProviderKey(arg1, arg2) {
  return window['go']['main']['App']['ChatSaveProviderKey'](arg1, arg2);
}

export function ClearBugPlatformLogin(arg1) {
  return window['go']['main']['App']['ClearBugPlatformLogin'](arg1);
}

export function DefaultDestPath(arg1, arg2) {
  return window['go']['main']['App']['DefaultDestPath'](arg1, arg2);
}

export function DeleteBugPlatform(arg1) {
  return window['go']['main']['App']['DeleteBugPlatform'](arg1);
}

export function DeleteInfraCred(arg1) {
  return window['go']['main']['App']['DeleteInfraCred'](arg1);
}

export function DetectAITools() {
  return window['go']['main']['App']['DetectAITools']();
}

export function DetectOpenClawModels(arg1) {
  return window['go']['main']['App']['DetectOpenClawModels'](arg1);
}

export function DetectSubmodulesForRepo(arg1) {
  return window['go']['main']['App']['DetectSubmodulesForRepo'](arg1);
}

export function Diff(arg1, arg2) {
  return window['go']['main']['App']['Diff'](arg1, arg2);
}

export function DiscoverBots(arg1) {
  return window['go']['main']['App']['DiscoverBots'](arg1);
}

export function Doctor(arg1, arg2) {
  return window['go']['main']['App']['Doctor'](arg1, arg2);
}

export function FetchBugByID(arg1) {
  return window['go']['main']['App']['FetchBugByID'](arg1);
}

export function FetchConfigContent(arg1) {
  return window['go']['main']['App']['FetchConfigContent'](arg1);
}

export function FetchConfigContentBatch(arg1) {
  return window['go']['main']['App']['FetchConfigContentBatch'](arg1);
}

export function ForgetGhostBot(arg1, arg2) {
  return window['go']['main']['App']['ForgetGhostBot'](arg1, arg2);
}

export function Gen(arg1, arg2) {
  return window['go']['main']['App']['Gen'](arg1, arg2);
}

export function GenPreview(arg1) {
  return window['go']['main']['App']['GenPreview'](arg1);
}

export function GenerateBugContext(arg1) {
  return window['go']['main']['App']['GenerateBugContext'](arg1);
}

export function GetMissingRepoPaths(arg1) {
  return window['go']['main']['App']['GetMissingRepoPaths'](arg1);
}

export function GetRemoteURL(arg1) {
  return window['go']['main']['App']['GetRemoteURL'](arg1);
}

export function GetRepoPathsForSystem(arg1) {
  return window['go']['main']['App']['GetRepoPathsForSystem'](arg1);
}

export function GetUserConfig() {
  return window['go']['main']['App']['GetUserConfig']();
}

export function ImportAndDeploy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportAndDeploy'](arg1, arg2, arg3, arg4, arg5);
}

export function KuboardFetchConfigMaps(arg1) {
  return window['go']['main']['App']['KuboardFetchConfigMaps'](arg1);
}

export function KuboardGetPodLogs(arg1) {
  return window['go']['main']['App']['KuboardGetPodLogs'](arg1);
}

export function KuboardListDeployments(arg1) {
  return window['go']['main']['App']['KuboardListDeployments'](arg1);
}

export function KuboardListEvents(arg1) {
  return window['go']['main']['App']['KuboardListEvents'](arg1);
}

export function KuboardListPods(arg1) {
  return window['go']['main']['App']['KuboardListPods'](arg1);
}

export function KuboardListResources(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['KuboardListResources'](arg1, arg2, arg3, arg4, arg5);
}

export function KuboardListServices(arg1) {
  return window['go']['main']['App']['KuboardListServices'](arg1);
}

export function KuboardPodSnapshot(arg1) {
  return window['go']['main']['App']['KuboardPodSnapshot'](arg1);
}

export function ListBotWorkspaceFiles(arg1) {
  return window['go']['main']['App']['ListBotWorkspaceFiles'](arg1);
}

export function ListBranchesForRepo(arg1) {
  return window['go']['main']['App']['ListBranchesForRepo'](arg1);
}

export function ListBugInvestigationRuns(arg1) {
  return window['go']['main']['App']['ListBugInvestigationRuns'](arg1);
}

export function ListBugPlatforms() {
  return window['go']['main']['App']['ListBugPlatforms']();
}

export function ListBugs() {
  return window['go']['main']['App']['ListBugs']();
}

export function ListGrafanaDatasources(arg1) {
  return window['go']['main']['App']['ListGrafanaDatasources'](arg1);
}

export function ListLokiLabelValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListLokiLabelValues'](arg1, arg2, arg3);
}

export function ListLokiLabels(arg1) {
  return window['go']['main']['App']['ListLokiLabels'](arg1);
}

export function LoadInfraCred(arg1) {
  return window['go']['main']['App']['LoadInfraCred'](arg1);
}

export function LoginBugPlatform(arg1) {
  return window['go']['main']['App']['LoginBugPlatform'](arg1);
}

export function MatchBugBots(arg1) {
  return window['go']['main']['App']['MatchBugBots'](arg1);
}

export function One2AllFetchConfigMaps(arg1, arg2, arg3) {
  return window['go']['main']['App']['One2AllFetchConfigMaps'](arg1, arg2, arg3);
}

export function One2AllListDeployments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['One2AllListDeployments'](arg1, arg2, arg3, arg4);
}

export function One2AllListResources(arg1, arg2, arg3) {
  return window['go']['main']['App']['One2AllListResources'](arg1, arg2, arg3);
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function OpenYAML() {
  return window['go']['main']['App']['OpenYAML']();
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function Plan(arg1) {
  return window['go']['main']['App']['Plan'](arg1);
}

export function PrefillCreds(arg1) {
  return window['go']['main']['App']['PrefillCreds'](arg1);
}

export function PreloadConfigCenter(arg1) {
  return window['go']['main']['App']['PreloadConfigCenter'](arg1);
}

export function PreviewBugAttachment(arg1) {
  return window['go']['main']['App']['PreviewBugAttachment'](arg1);
}

export function ProbeDataStore(arg1) {
  return window['go']['main']['App']['ProbeDataStore'](arg1);
}

export function ProbeURL(arg1) {
  return window['go']['main']['App']['ProbeURL'](arg1);
}

export function ProbeURLAuth(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProbeURLAuth'](arg1, arg2, arg3, arg4);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadBotWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadBotWorkspaceFile'](arg1, arg2);
}

export function ReadEnv(arg1) {
  return window['go']['main']['App']['ReadEnv'](arg1);
}

export function RecommendRoleForRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecommendRoleForRepo'](arg1, arg2, arg3);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function RunInstall(arg1, arg2) {
  return window['go']['main']['App']['RunInstall'](arg1, arg2);
}

export function SaveBugPlatform(arg1) {
  return window['go']['main']['App']['SaveBugPlatform'](arg1);
}

export function SaveInfraCred(arg1, arg2) {
  return window['go']['main']['App']['SaveInfraCred'](arg1, arg2);
}

export function SaveInfraCredBatch(arg1) {
  return window['go']['main']['App']['SaveInfraCredBatch'](arg1);
}

export function SaveRepoPathsForSystem(arg1, arg2) {
  return window['go']['main']['App']['SaveRepoPathsForSystem'](arg1, arg2);
}

export function SaveYAML(arg1, arg2) {
  return window['go']['main']['App']['SaveYAML'](arg1, arg2);
}

export function ScanInstallPrompts(arg1) {
  return window['go']['main']['App']['ScanInstallPrompts'](arg1);
}

export function SelfTestAgent(arg1) {
  return window['go']['main']['App']['SelfTestAgent'](arg1);
}

export function SetDefaultReposRoot(arg1) {
  return window['go']['main']['App']['SetDefaultReposRoot'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartBugInvestigation(arg1) {
  return window['go']['main']['App']['StartBugInvestigation'](arg1);
}

export function SyncBugPlatform(arg1) {
  return window['go']['main']['App']['SyncBugPlatform'](arg1);
}

export function UninstallAgent(arg1) {
  return window['go']['main']['App']['UninstallAgent'](arg1);
}

export function UninstallBot(arg1, arg2) {
  return window['go']['main']['App']['UninstallBot'](arg1, arg2);
}

export function Validate(arg1) {
  return window['go']['main']['App']['Validate'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WriteBotWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteBotWorkspaceFile'](arg1, arg2, arg3);
}
