// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2, arg3) {
  return window['go']['main']['App']['Analyze'](arg1, arg2, arg3);
}

export function ApplyBot(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyBot'](arg1, arg2, arg3);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function ChatCheckKey(arg1, arg2) {
  return window['go']['main']['App']['ChatCheckKey'](arg1, arg2);
}

export function ChatContextFor(arg1) {
  return window['go']['main']['App']['ChatContextFor'](arg1);
}

export function ChatSend(arg1) {
  return window['go']['main']['App']['ChatSend'](arg1);
}

export function ChatStop(arg1) {
  return window['go']['main']['App']['ChatStop'](arg1);
}

export function DefaultDestPath(arg1, arg2) {
  return window['go']['main']['App']['DefaultDestPath'](arg1, arg2);
}

export function Diff(arg1, arg2) {
  return window['go']['main']['App']['Diff'](arg1, arg2);
}

export function DiscoverBots(arg1) {
  return window['go']['main']['App']['DiscoverBots'](arg1);
}

export function Doctor(arg1, arg2) {
  return window['go']['main']['App']['Doctor'](arg1, arg2);
}

export function Gen(arg1, arg2) {
  return window['go']['main']['App']['Gen'](arg1, arg2);
}

export function ImportAndDeploy(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportAndDeploy'](arg1, arg2, arg3);
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function OpenYAML() {
  return window['go']['main']['App']['OpenYAML']();
}

export function Plan(arg1) {
  return window['go']['main']['App']['Plan'](arg1);
}

export function ReadEnv(arg1) {
  return window['go']['main']['App']['ReadEnv'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function RunInstall(arg1, arg2) {
  return window['go']['main']['App']['RunInstall'](arg1, arg2);
}

export function SaveYAML(arg1, arg2) {
  return window['go']['main']['App']['SaveYAML'](arg1, arg2);
}

export function ScanInstallPrompts(arg1) {
  return window['go']['main']['App']['ScanInstallPrompts'](arg1);
}

export function Validate(arg1) {
  return window['go']['main']['App']['Validate'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
