// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyzerpipe} from '../models';
import {main} from '../models';
import {agent} from '../models';
import {analyzer} from '../models';
import {generator} from '../models';
import {discover} from '../models';
import {doctor} from '../models';
import {cchub} from '../models';
import {labelprobe} from '../models';
import {dsprobe} from '../models';
import {deploy} from '../models';

export function Analyze(arg1:string,arg2:string,arg3:boolean):Promise<analyzerpipe.Result>;

export function AnalyzeV2(arg1:main.AnalyzeInput):Promise<analyzerpipe.Result>;

export function ApplyBot(arg1:string,arg2:string,arg3:boolean):Promise<agent.Result>;

export function CancelInstall():Promise<boolean>;

export function ChatDeleteKey(arg1:string):Promise<void>;

export function ChatDeleteProviderKey(arg1:string):Promise<void>;

export function ChatLoadKey(arg1:string):Promise<main.ChatLoadKeyResult>;

export function ChatLoadProviderKey(arg1:string):Promise<main.ChatLoadKeyResult>;

export function ChatSaveKey(arg1:string,arg2:string):Promise<void>;

export function ChatSaveProviderKey(arg1:string,arg2:string):Promise<void>;

export function DefaultDestPath(arg1:string,arg2:string):Promise<string>;

export function DeleteInfraCred(arg1:string):Promise<void>;

export function DetectAITools():Promise<main.AIToolsDetectResult>;

export function DetectOpenClawModels(arg1:string):Promise<main.OpenClawDetectResult>;

export function DetectSubmodulesForRepo(arg1:string):Promise<Array<analyzer.SubmoduleHint>>;

export function Diff(arg1:string,arg2:string):Promise<generator.Plan>;

export function DiscoverBots(arg1:Array<string>):Promise<Array<discover.DiscoveredAgent>>;

export function Doctor(arg1:string,arg2:string):Promise<doctor.Report>;

export function FetchConfigContent(arg1:main.CCHubFetchContentInput):Promise<cchub.FetchContentResult>;

export function FetchConfigContentBatch(arg1:main.CCHubFetchBatchInput):Promise<cchub.FetchBatchResult>;

export function ForgetGhostBot(arg1:string,arg2:string):Promise<void>;

export function Gen(arg1:string,arg2:string):Promise<generator.GenSummary>;

export function GenPreview(arg1:string):Promise<main.GenPreviewResult>;

export function GetMissingRepoPaths(arg1:string):Promise<main.MissingRepoPathsResult>;

export function GetRemoteURL(arg1:string):Promise<string>;

export function GetRepoPathsForSystem(arg1:string):Promise<Record<string, string>>;

export function GetUserConfig():Promise<main.UserConfigResult>;

export function ImportAndDeploy(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:Record<string, string>):Promise<agent.Result>;

export function KuboardFetchConfigMaps(arg1:main.KuboardFetchBatchInput):Promise<main.KuboardFetchBatchResult>;

export function KuboardGetPodLogs(arg1:main.KuboardGetPodLogsInput):Promise<string>;

export function KuboardListDeployments(arg1:main.KuboardListPodsInput):Promise<Array<main.KuboardDeploymentInfo>>;

export function KuboardListEvents(arg1:main.KuboardListEventsInput):Promise<Array<main.KuboardEvent>>;

export function KuboardListPods(arg1:main.KuboardListPodsInput):Promise<Array<main.KuboardPodInfo>>;

export function KuboardListResources(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.KuboardResources>;

export function KuboardListServices(arg1:main.KuboardListPodsInput):Promise<Array<main.KuboardServiceInfo>>;

export function KuboardPodSnapshot(arg1:main.KuboardPodSnapshotInput):Promise<main.KuboardPodSnapshotResult>;

export function ListBotWorkspaceFiles(arg1:string):Promise<main.FileNode>;

export function ListBranchesForRepo(arg1:string):Promise<Array<string>>;

export function ListGrafanaDatasources(arg1:main.LokiAuthInput):Promise<Array<labelprobe.Datasource>>;

export function ListLokiLabelValues(arg1:main.LokiAuthInput,arg2:string,arg3:string):Promise<labelprobe.ValuesResult>;

export function ListLokiLabels(arg1:main.LokiAuthInput):Promise<labelprobe.LabelsResult>;

export function LoadInfraCred(arg1:string):Promise<main.ChatLoadKeyResult>;

export function OpenDir(arg1:string):Promise<string>;

export function OpenYAML():Promise<main.OpenYAMLResult>;

export function PathExists(arg1:string):Promise<boolean>;

export function Plan(arg1:string):Promise<generator.Plan>;

export function PrefillCreds(arg1:string):Promise<Record<string, string>>;

export function PreloadConfigCenter(arg1:main.CCHubPreloadInput):Promise<cchub.Result>;

export function ProbeDataStore(arg1:main.DSProbeInput):Promise<dsprobe.Result>;

export function ProbeURL(arg1:string):Promise<dsprobe.Result>;

export function ProbeURLAuth(arg1:string,arg2:string,arg3:string,arg4:string):Promise<dsprobe.Result>;

export function ReadBotWorkspaceFile(arg1:string,arg2:string):Promise<main.ReadFileResult>;

export function ReadEnv(arg1:string):Promise<Record<string, string>>;

export function RecommendRoleForRepo(arg1:string,arg2:string,arg3:string):Promise<analyzer.RoleHint>;

export function RevealInFinder(arg1:string):Promise<void>;

export function RunInstall(arg1:string,arg2:Record<string, string>):Promise<main.RunInstallResult>;

export function SaveInfraCred(arg1:string,arg2:string):Promise<void>;

export function SaveInfraCredBatch(arg1:main.InfraCredBatchInput):Promise<void>;

export function SaveRepoPathsForSystem(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SaveYAML(arg1:string,arg2:string):Promise<string>;

export function ScanInstallPrompts(arg1:string):Promise<Array<deploy.Prompt>>;

export function SelfTestAgent(arg1:string):Promise<agent.SelfTestResult>;

export function SetDefaultReposRoot(arg1:string):Promise<void>;

export function UninstallAgent(arg1:string):Promise<agent.UninstallOpenclawResult>;

export function UninstallBot(arg1:string,arg2:string):Promise<main.UninstallBotResult>;

export function Validate(arg1:string):Promise<main.ValidateResult>;

export function Version():Promise<string>;

export function WriteBotWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<void>;
