#!/usr/bin/env bash
# 把 $BIN 打成 $BUNDLE_DIR/.app（macOS GUI app 包）。
# 由 Makefile 的 desktop-app target 调用。裸二进制双击会被 Terminal 启动，
# .app 包里有 Info.plist + MacOS/ 目录 macOS 才认它是 GUI app。
#
# 需要的环境变量:
#   BIN          源二进制绝对路径（如 bin/tshoot-desktop）
#   BUNDLE_DIR   目标 .app 目录
#   BUNDLE_NAME  bundle 内可执行文件名（CFBundleExecutable）
#   BUNDLE_ID    bundle identifier（反向 DNS）
#   VERSION      版本串
#   ICON_SRC     1024x1024 PNG 源（可选；缺就没图标）
#   BROWSER_RUNTIME_SRC 已完成真实 probe 的固定 Chromium 运行时目录
set -euo pipefail

: "${BIN:?BIN required}"
: "${BUNDLE_DIR:?BUNDLE_DIR required}"
: "${BUNDLE_NAME:?BUNDLE_NAME required}"
: "${BUNDLE_ID:?BUNDLE_ID required}"
: "${VERSION:=dev}"
: "${BROWSER_RUNTIME_SRC:?BROWSER_RUNTIME_SRC required}"

if [[ ! -d "$BROWSER_RUNTIME_SRC" || -L "$BROWSER_RUNTIME_SRC" \
   || ! -f "$BROWSER_RUNTIME_SRC/.runtime-ready.json" \
   || ! -d "$BROWSER_RUNTIME_SRC/node_modules/playwright" \
   || ! -d "$BROWSER_RUNTIME_SRC/browsers" ]]; then
  echo "✗ BROWSER_RUNTIME_SRC 不是已就绪的固定浏览器运行时: $BROWSER_RUNTIME_SRC" >&2
  exit 1
fi

rm -rf "$BUNDLE_DIR"
mkdir -p "$BUNDLE_DIR/Contents/MacOS" "$BUNDLE_DIR/Contents/Resources"

cp "$BIN" "$BUNDLE_DIR/Contents/MacOS/$BUNDLE_NAME"
chmod +x "$BUNDLE_DIR/Contents/MacOS/$BUNDLE_NAME"

# Chromium 在发布机构建/探测并随 App 交付。用户首次启动只从这里原子导入
# ~/.tshoot，不再依赖现场网络；裸 desktop 二进制仍保留联网兜底。
mkdir -p "$BUNDLE_DIR/Contents/Resources/browser-runtime"
cp -R "$BROWSER_RUNTIME_SRC" "$BUNDLE_DIR/Contents/Resources/browser-runtime/"

# 图标（可选）：把 1024x1024 PNG 转成多尺寸 .icns
if [[ -n "${ICON_SRC:-}" && -f "$ICON_SRC" ]] \
   && command -v sips >/dev/null 2>&1 \
   && command -v iconutil >/dev/null 2>&1; then
  tmp=$(mktemp -d)
  mkdir -p "$tmp/icon.iconset"
  for sz in 16 32 64 128 256 512; do
    sips -z "$sz" "$sz" "$ICON_SRC" --out "$tmp/icon.iconset/icon_${sz}x${sz}.png" >/dev/null 2>&1 || true
    dbl=$((sz*2))
    sips -z "$dbl" "$dbl" "$ICON_SRC" --out "$tmp/icon.iconset/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1 || true
  done
  iconutil -c icns "$tmp/icon.iconset" -o "$BUNDLE_DIR/Contents/Resources/icon.icns" 2>/dev/null || true
  rm -rf "$tmp"
fi

cat > "$BUNDLE_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Troubleshooter Studio</string>
  <key>CFBundleDisplayName</key><string>Troubleshooter Studio</string>
  <key>CFBundleExecutable</key><string>${BUNDLE_NAME}</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>${VERSION}</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>LSMinimumSystemVersion</key><string>10.13.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSHumanReadableCopyright</key><string>Generated by troubleshooter-studio</string>
</dict>
</plist>
PLIST

echo "✓ $BUNDLE_DIR"
echo "  打开: open '$BUNDLE_DIR'"
echo "  装到系统: cp -R '$BUNDLE_DIR' /Applications/"
